ignore:
  - "**/cog_settings.py"
  - "**/*_pb2.py"
  - "**/CogSettings.?s"
  - "**/CogSettings.d.ts"
  - "**/*_pb.?s"
  - "**/*_pb.d.ts"
  - "**/*_pb_service.?s"
  - "**/*_pb_service.d.ts"
  - "**/node_modules/**"
  - "**/.venv/**"
license:
  CopyrightYear: 2021
  Author: "AI Redefined Inc. <dev+cogment@ai-r.com>"
