
version: '3.7'

services:
  grpc-cli:
    image: namely/grpc-cli:1.28_1

  random_agent:
    build:
      context: random_agent
      dockerfile: ../py_service.dockerfile
    environment:
      - PYTHONUNBUFFERED=1

  environment:
    build:
      context: environment
      dockerfile: ../py_service.dockerfile
    environment:
      - PYTHONUNBUFFERED=1

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.dockerfile
    ports:
      - "9000:9000"

  client:
    build:
      context: client
      dockerfile: ../py_service.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  web-client:
    volumes:
      - ./web-client:/app
    build:
      context: web-client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_APP_VERSION=dev
    stdin_open: true
    ports:
      - "3000:3000"

  grpcwebproxy:
    build:
      context: ./grpcwebproxy
    restart: on-failure
    ports:
      - "8080:8080"