launch_python: &py_launch
  - [".venv/bin/python", "-m", "main"]

# When used in "cogment launch services.yaml",
# these scripts will run in parallel, all stopping as 
# soon as any of them terminates.
scripts:
  orchestrator:
    environment:
      COGMENT_ORCHESTRATOR_ACTOR_PORT: "{{.ORCHESTRATOR_PORT}}"
    commands: 
      - ["cogment", "services", "orchestrator"]
  
  environment:
    dir: "environment"
    commands: *py_launch
  
  random_agent:
    dir: "random_agent"
    commands: *py_launch

  dqn_agent:
    dir: "dqn_agent"
    commands: *py_launch