version: "3.7"

services:
  grpc-cli:
    image: namely/grpc-cli:1.28_1
  random-agent:
    build:
      context: random_agent
      dockerfile: ../py_service.dockerfile
    environment:
      - COGMENT_GRPC_REFLECTION=1
      - PYTHONUNBUFFERED=1

  environment:
    build:
      context: environment
      dockerfile: ../py_service.dockerfile
    environment:
      - COGMENT_GRPC_REFLECTION=1
      - PYTHONUNBUFFERED=1

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - environment
      - random-agent

  client:
    build:
      context: client
      dockerfile: ../py_service.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    depends_on:
      - orchestrator

  dashboard:
    image: cogment/dashboard:v1.2.3
    ports:
      - 3003:3000/tcp
    depends_on:
      - metrics

  metrics:
    user: 0:0
    image: cogment/metrics:v1.2.3
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./metrics/data:/prometheus
    ports:
      - 9090:9090/tcp


